name: blocky
description: A casual 3D block-stacking game built with Flutter.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  audioplayers: ^6.8.1
  flutter:
    sdk: flutter

  flutter_scene: ^0.23.0
  flutter_scene_rapier: ^0.5.1
  shared_preferences: ^2.5.5
  vector_math: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/audio/
    - assets/fonts/

  fonts:
    - family: ArcadePixel
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf